### ISSUE TITLE
Lualine Support

### ISSUE THREAD

**Issue by Trid-collab** [rebelot/kanagawa.nvim#35]
I have been using your colorscheme for sometime now, but couldn't get to activate the lualine support. I have put the lualine theme option in auto , but the statusline colors seems to muted. Is that it is supposed to be.

**Comment by rebelot** [comment]
I personally don't use lualine, so I'll need @jasonrhansen to look into this.

**Comment by Trid-collab** [comment]
> there's no need to put it in auto. This probably has to do with the order in which you load plugins with packer. Lualine should be loaded after the colorscheme.

Just curious, could you share how do you get the statusline as shown in the screenshots

**Comment by rebelot** [comment]
It's rebelot/heirline ;)

**Comment by jasonrhansen** [comment]
The lualine theme in this repo is definitely more minimalist than what @rebelot uses for heirline. However, the colors used should still match the syntax theme. If you want to get the statusline that @rebelot uses, it's going to require you to configure it yourself since heirline doesn't provide a default statusline. I suggest you look [here](https://github.com/rebelot/dotfiles/blob/master/nvim/lua/plugins/heirline.lua) to see how @rebelot does it.
